### ISSUE TITLE
Crash occurs when MouseToJoy sends output at same time as other plugins

### ISSUE THREAD

**Issue by Osjur** [evilC/UCR#64] opened 2016-01-01 20:47 UTC
Bug1: Mouse and KB hooks hang if I rapidly press WASD which have been remapped to vJoy axis X & Y and mouse to joy axis plugin has been enabled and mapped to other axis, in my case to Z and RZ.

Exception was caused in thread id: 4440
Line:656
UCR.ahk

![bug1](https://cloud.githubusercontent.com/assets/9019921/12072086/9c54c93e-b0d8-11e5-83cb-17589f071331.png)

Bug2: UCR crashes if I press WASD which have been remapped to axis (X), hold the key down and move mouse which has also been remapped to different axis (Z)

**Comment by evilC** [comment] 2016-01-02 15:09
I can't get the access violation dialog to show in this case, but I can cause a crash.

I think i have an idea what is causing this, but I am gonna have to ask a friend for some help on this one I think.

I *suspect* it is caused by one input happening before another has had time to finish processing.

I think I will need to move to "Critical Objects" to ensure this does not happen, which may involve a bit of a redesign.

**Comment by evilC** [comment] 2016-01-02 20:23
HotkeyIt and I just spent about 4 hours investigating this, and the finger of blame is firmly pointing at the MouseToJoy plugin.

The fix we have in mind should be fairly simple, and I will try to implement it tomorrow.

In the meantime, if you can make this error happen without using a MouseToJoy plugin, please let me know.
For me, the steps to reproduce are:
1) Add a ButtonToButton plugin, configure A to send 1
2) Add a MouseToJoy plugin, configure the X axis to operate vJoy stick 1 X axis
3) Spam A at the same time as moving the mouse horizontally

For future reference, please specify which plugins you are using rather than saying "I mapped this to that". It was obvious in this case, but could cause confusion in future.

**Comment by Osjur** [comment] 2016-01-03 09:25
I can make it crash right away with your method.

**Comment by evilC** [comment] 2016-01-03 13:55
Bug 5 (Remapping)
This is not a bug, it's a feature. If you wish to hide the input from windows, drop down the input box and select "Block: On".
You may not always wish to, and until I have per-application options in (ie the ability to say "these keys only get remapped in this game"), then defaulting to block:off is safer as when block is on, *no app* will see that key change - if you remapped w to e, then w would stop working in windows, period.
Once I have the "Associated App" (Profile hotkeys only take effect in a certain app) then I may default to block:on.

**Comment by evilC** [comment] 2016-01-03 16:29
I just sat down and fixed this bug, but it does not solve the underlying problem.
I can also repro this bug without using a MouseToJoy plugin:

1) Add a ButtonToButton plugin to the Global profile. Bind the input to a
2) Add a ButtonToButton plugin to the Default profile. Bind the input to d
Hit A+D together.

This is because the input detection for the Global and the Default profile are handled in separate threads.
Both threads then try to call InputEvent in the main thread at the same time - boom.

So the problem is that UCR uses multiple threads, but is not "Thread Safe".

This problem can also be highlighted in other ways. eg:
Add an AxisToAxis plugin, bind it to a stick axis.
Then, while waggling the axis, try to use the UI for other things (eg adding other plugins, changing plugin settings) - you can cause odd things to happen.

**Comment by evilC** [comment] 2016-01-20 20:42
I just released a new version of UCR which should hopefully fix the access violation crashes.
Please see the [forum thread](https://autohotkey.com/boards/viewtopic.php?f=19&t=12249).

**Comment by evilC** [comment] 2016-07-30 19:37
No reports of this for a while, it seems that the fix worked. Closing.

**Closed by evilC** 2016-07-30 19:37 UTC
Labels: bug, help wanted
